In [1]:
import pandas as pd
import numpy as np
import glob
import os

Uploading the upward generated timeseries:

In [2]:
upward =pd.read_csv("Data/upward.csv")

I look at the initial price at time step 0 and the final price of the stock to calculate the optimal portfolio value at final timestep and the optimal allocation for each timestep:

In [27]:
upward.loc[upward['tic'] == 'STOCK'].iloc[:991]

            date    tic  close
1000  2023-01-01  STOCK    100
1001  2023-01-02  STOCK    101
1002  2023-01-03  STOCK    102
1003  2023-01-04  STOCK    103
1004  2023-01-05  STOCK    104
...          ...    ...    ...
1986  2025-09-13  STOCK   1086
1987  2025-09-14  STOCK   1087
1988  2025-09-15  STOCK   1088
1989  2025-09-16  STOCK   1089
1990  2025-09-17  STOCK   1090

[991 rows x 3 columns]

The stock price starts from 101. I exclude the first price of 100 because the first initialization is fixed to 0.5, 0.5 (and then the porftolio value of day 1 considering the environments.py logics becomes fixed to 1005). So we can look at the stock price (101) from the second timestep to see what could be the maximum achievable portfolio value starting from 1005. So given that the stock price starts at 101 and ends up at 1090, the optimal portfolio value would be:

In [4]:
C = 1005
weight = 1
R = 1090/101
v = C * (weight * R + (1-weight)* 1)
v

10846.039603960397

I check that this final optimal portfolio value is the same for a run that I know it was the optimal allocation sequence and that the allocation weights are always 0,1 except for the first timestep, so that I can use this to as the optimal baseline to calculate the metrics later:

In [5]:
upward_run_work = pd.read_csv("Results/4_1/ddpg/upward/training_logs/03.csv")

Taking the first 990 days to make it comparable with experiment 3 (but episode 500 instead of 50):

In [6]:
upward_run_work.loc[(upward_run_work['episode'] == 500)].iloc[:990]

,episode,day,actions,allocation_weights,portfolio_return,reward,new_portfolio_value
498501,500,1,"0.50, 0.50","0.50, 0.50",0.50%,1005.00,"1,005"
498502,500,2,"0.00, 1.00","0.00, 1.00",0.99%,1014.95,"1,015"
498503,500,3,"0.00, 1.00","0.00, 1.00",0.98%,1024.90,"1,025"
498504,500,4,"0.00, 1.00","0.00, 1.00",0.97%,1034.85,"1,035"
498505,500,5,"0.00, 1.00","0.00, 1.00",0.96%,1044.80,"1,045"
...,...,...,...,...,...,...,...
499486,500,986,"0.00, 1.00","0.00, 1.00",0.09%,10806.24,"10,806"
499487,500,987,"0.00, 1.00","0.00, 1.00",0.09%,10816.19,"10,816"
499488,500,988,"0.00, 1.00","0.00, 1.00",0.09%,10826.14,"10,826"
499489,500,989,"0.00, 1.00","0.00, 1.00",0.09%,10836.09,"10,836"
499490,500,990,"0.00, 1.00","0.00, 1.00",0.09%,10846.04,"10,846"

In [7]:
optimal_upward_df = upward_run_work.loc[(upward_run_work['episode'] == 500)].iloc[:990].loc[:, ['day', 'allocation_weights', 'new_portfolio_value']]

In [8]:
assert (optimal_upward_df['allocation_weights'].iloc[1:] == "0.00, 1.00").all()

In [9]:
optimal_upward_df['new_portfolio_value'].iloc[-1] # final portfolio value as above

'10,846'

For the downward trend, it is trivial that the optimal portfolio value stays 1000:

In [10]:
C = 1000
weight = 0
R = 999/9
v = C * (weight * R + (1-weight)* 1)
v

1000.0

In [11]:
downward = pd.read_csv("Data/downward.csv")

In [12]:
downward.loc[downward['tic'] == 'STOCK'].iloc[1:992] #da 999 a 9

            date    tic  close
1001  2023-01-02  STOCK    999
1002  2023-01-03  STOCK    998
1003  2023-01-04  STOCK    997
1004  2023-01-05  STOCK    996
1005  2023-01-06  STOCK    995
...          ...    ...    ...
1987  2025-09-14  STOCK     13
1988  2025-09-15  STOCK     12
1989  2025-09-16  STOCK     11
1990  2025-09-17  STOCK     10
1991  2025-09-18  STOCK      9

[991 rows x 3 columns]

I construct the optimal downward df baseline as well (to be used in the metrics calculation):

In [13]:
downward_run_work = pd.read_csv("Results/4_1/ddpg/downward/training_logs/07.csv")

Taking the first 990 days to make it comparable with experiment 3 (but episode 500 instead of 50):

In [14]:
optimal_downward_df = downward_run_work.loc[(downward_run_work['episode'] == 500)].iloc[:990].loc[:, ['day', 'allocation_weights', 'new_portfolio_value']]

In [15]:
optimal_downward_df

        day allocation_weights new_portfolio_value
498501    1         0.50, 0.50               1,000
498502    2         1.00, 0.00               1,000
498503    3         1.00, 0.00               1,000
498504    4         1.00, 0.00               1,000
498505    5         1.00, 0.00               1,000
...     ...                ...                 ...
499486  986         1.00, 0.00               1,000
499487  987         1.00, 0.00               1,000
499488  988         1.00, 0.00               1,000
499489  989         1.00, 0.00               1,000
499490  990         1.00, 0.00               1,000

[990 rows x 3 columns]

In [16]:
periodic_df = pd.read_csv("Data/periodic.csv")

In [17]:
periodic_df.loc[periodic_df['tic'] =='STOCK'].iloc[:5]

            date    tic       close
1000  2023-01-01  STOCK  500.000000
1001  2023-01-02  STOCK  500.000000
1002  2023-01-03  STOCK  507.471907
1003  2023-01-04  STOCK  514.776010
1004  2023-01-05  STOCK  521.748277

Here I mimic the logic of what would be written in the training_logs csv files if the optimal allocation would be chosen, to obtain the optimal baseline df for the periodic trend generator: (look at timesteps_debug_periodic_alloc.txt to understand)

In [ ]:
class PeriodicTrendPriceGenerator:
    def __init__(self, start=500, amplitude=50, frequency=0.15):
        self.start = start
        self.amplitude = amplitude
        self.frequency = frequency
        self.t = 0

    def generate_price(self, last_price=None):
        value = self.amplitude * np.sin(self.frequency * self.t) + self.start
        self.t += 1
        return value

# Generate 991 days of stock prices to make it comparable with experiment 3:
days = 990 
generator = PeriodicTrendPriceGenerator(start= 500, amplitude=50, frequency=0.15)
stock_prices = [generator.generate_price() for _ in range(days)]
stock_prices = [500] + stock_prices
stock_prices = np.array(stock_prices)
allocation = [0.5,0.5]
portfolio_value = 1000
days_df = []
optimal_allocations = []
optimal_portfolio_values = []

for day, stock_price in enumerate(stock_prices):
    print("day: ", day)
    if day == 0:
       pass
    else:
        if day == 1:
           
            pass
        old_allocation = allocation
        
        print("stock price today", stock_prices[day])
        print("stock price yesterday", stock_prices[day-1])
        portfolio_return = sum((np.array([500, stock_prices[day]]) / np.array([500, stock_prices[day-1]])-1)*np.array(old_allocation))
        new_portfolio_value = portfolio_value*(1+portfolio_return)
        portfolio_value = new_portfolio_value
        print("portfolio_value", portfolio_value)
        if (stock_prices[day] >= stock_prices[day-1]):
            allocation = [0, 1]
        else:
            allocation = [1, 0]
        print("old_allocation", old_allocation)
        print("allocation:", allocation)
        days_df.append(day)
        optimal_allocations.append(old_allocation)
        optimal_portfolio_values.append(portfolio_value)

optimal_periodic_df = pd.DataFrame({"day": days_df,
                                            "allocation_weights":optimal_allocations,
                                            "new_portfolio_value": optimal_portfolio_values
                                           })

day:  0
day:  1
stock price today 500.0
stock price yesterday 500.0
portfolio_value 1000.0
old_allocation [0.5, 0.5]
allocation: [0, 1]
day:  2
stock price today 507.47190662367996
stock price yesterday 500.0
portfolio_value 1014.9438132473598
old_allocation [0, 1]
allocation: [0, 1]
day:  3
stock price today 514.776010333067
stock price yesterday 507.47190662367996
portfolio_value 1029.552020666134
old_allocation [0, 1]
allocation: [0, 1]
day:  4
stock price today 521.7482767055615
stock price yesterday 514.776010333067
portfolio_value 1043.496553411123
old_allocation [0, 1]
allocation: [0, 1]
day:  5
stock price today 528.2321236697518
stock price yesterday 521.7482767055615
portfolio_value 1056.4642473395036
old_allocation [0, 1]
allocation: [0, 1]
day:  6
stock price today 534.0819380011667
stock price yesterday 528.2321236697518
portfolio_value 1068.1638760023336
old_allocation [0, 1]
allocation: [0, 1]
day:  7
stock price today 539.1663454813742
stock price yesterday 534.0819380011667
portfolio_value 1078.3326909627485
old_allocation [0, 1]
allocation: [0, 1]
day:  8
stock price today 543.3711612797008
stock price yesterday 539.1663454813742
portfolio_value 1086.7423225594018
old_allocation [0, 1]
allocation: [0, 1]
day:  9
stock price today 546.6019542983613
stock price yesterday 543.3711612797008
portfolio_value 1093.2039085967228
old_allocation [0, 1]
allocation: [0, 1]
day:  10
stock price today 548.786167891333
stock price yesterday 546.6019542983613
portfolio_value 1097.5723357826662
old_allocation [0, 1]
allocation: [0, 1]
day:  11
stock price today 549.8747493302027
stock price yesterday 548.786167891333
portfolio_value 1099.7494986604056
old_allocation [0, 1]
allocation: [0, 1]
day:  12
stock price today 549.843251422696
stock price yesterday 549.8747493302027
portfolio_value 1099.6865028453922
old_allocation [0, 1]
allocation: [1, 0]
day:  13
stock price today 548.6923815439097
stock price yesterday 549.843251422696
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  14
stock price today 546.4479857501934
stock price yesterday 548.6923815439097
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  15
stock price today 543.1604683324437
stock price yesterday 546.4479857501934
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  16
stock price today 538.9036598443961
stock price yesterday 543.1604683324437
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  17
stock price today 533.7731590275575
stock price yesterday 538.9036598443961
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  18
stock price today 527.8841858695708
stock price yesterday 533.7731590275575
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  19
stock price today 521.3689940116915
stock price yesterday 527.8841858695708
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  20
stock price today 514.3739006171272
stock price yesterday 521.3689940116915
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  21
stock price today 507.05600040299333
stock price yesterday 514.3739006171272
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  22
stock price today 499.5796376316426
stock price yesterday 507.05600040299333
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  23
stock price today 492.1127152928376
stock price yesterday 499.5796376316426
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  24
stock price today 484.82292436457857
stock price yesterday 492.1127152928376
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  25
stock price today 477.8739778352574
stock price yesterday 484.82292436457857
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  26
stock price today 471.4219340628828
stock price yesterday 477.8739778352574
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  27
stock price today 465.6116920408013
stock price yesterday 471.4219340628828
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  28
stock price today 460.57373727869026
stock price yesterday 465.6116920408013
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  29
stock price today 456.4212113793206
stock price yesterday 460.57373727869026
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  30
stock price today 453.24737112207754
stock price yesterday 456.4212113793206
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  31
stock price today 451.1234941167452
stock price yesterday 453.24737112207754
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  32
stock price today 450.09727806205603
stock price yesterday 451.1234941167452
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  33
stock price today 450.19176955820797
stock price yesterday 450.09727806205603
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [0, 1]
day:  34
stock price today 451.404846529909
stock price yesterday 450.19176955820797
portfolio_value 1102.649694229369
old_allocation [0, 1]
allocation: [0, 1]
day:  35
stock price today 453.7092658836134
stock price yesterday 451.404846529909
portfolio_value 1108.2787150856395
old_allocation [0, 1]
allocation: [0, 1]
day:  36
stock price today 457.0532753286704
stock price yesterday 453.7092658836134
portfolio_value 1116.4471497412208
old_allocation [0, 1]
allocation: [0, 1]
day:  37
stock price today 461.36177562220064
stock price yesterday 457.0532753286704
portfolio_value 1126.9715527638486
old_allocation [0, 1]
allocation: [0, 1]
day:  38
stock price today 466.5380071361869
stock price yesterday 461.36177562220064
portfolio_value 1139.6155687509015
old_allocation [0, 1]
allocation: [0, 1]
day:  39
stock price today 472.4657228701181
stock price yesterday 466.5380071361869
portfolio_value 1154.0952403621916
old_allocation [0, 1]
allocation: [0, 1]
day:  40
stock price today 479.01179910800704
stock price yesterday 472.4657228701181
portfolio_value 1170.085385389649
old_allocation [0, 1]
allocation: [0, 1]
day:  41
stock price today 486.0292250900537
stock price yesterday 479.01179910800704
portfolio_value 1187.2268996486641
old_allocation [0, 1]
allocation: [0, 1]
day:  42
stock price today 493.3604045573741
stock price yesterday 486.0292250900537
portfolio_value 1205.1348216838917
old_allocation [0, 1]
allocation: [0, 1]
day:  43
stock price today 500.8406950242175
stock price yesterday 493.3604045573741
portfolio_value 1223.4069781736098
old_allocation [0, 1]
allocation: [0, 1]
day:  44
stock price today 508.30210529324785
stock price yesterday 500.8406950242175
portfolio_value 1241.6330158754913
old_allocation [0, 1]
allocation: [0, 1]
day:  45
stock price today 515.5770681756688
stock price yesterday 508.30210529324785
portfolio_value 1259.403617275758
old_allocation [0, 1]
allocation: [0, 1]
day:  46
stock price today 522.5022036890309
stock price yesterday 515.5770681756688
portfolio_value 1276.3196929781036
old_allocation [0, 1]
allocation: [0, 1]
day:  47
stock price today 528.92198821941
stock price yesterday 522.5022036890309
portfolio_value 1292.001344391148
old_allocation [0, 1]
allocation: [0, 1]
day:  48
stock price today 534.6922472464881
stock price yesterday 528.92198821941
portfolio_value 1306.0963954317895
old_allocation [0, 1]
allocation: [0, 1]
day:  49
stock price today 539.6833931924576
stock price yesterday 534.6922472464881
portfolio_value 1318.288301640782
old_allocation [0, 1]
allocation: [0, 1]
day:  50
stock price today 543.7833356796441
stock price yesterday 539.6833931924576
portfolio_value 1328.3032590888622
old_allocation [0, 1]
allocation: [0, 1]
day:  51
stock price today 546.8999988387369
stock price yesterday 543.7833356796441
portfolio_value 1335.916353422713
old_allocation [0, 1]
allocation: [0, 1]
day:  52
stock price today 548.96338913431
stock price yesterday 546.8999988387369
portfolio_value 1340.9566109564537
old_allocation [0, 1]
allocation: [0, 1]
day:  53
stock price today 549.9271672687303
stock price yesterday 548.96338913431
portfolio_value 1343.3108383720273
old_allocation [0, 1]
allocation: [0, 1]
day:  54
stock price today 549.769688862881
stock price yesterday 549.9271672687303
portfolio_value 1342.926164797093
old_allocation [0, 1]
allocation: [1, 0]
day:  55
stock price today 548.4944905422543
stock price yesterday 549.769688862881
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  56
stock price today 546.130210511967
stock price yesterday 548.4944905422543
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  57
stock price today 542.729945404414
stock price yesterday 546.130210511967
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  58
stock price today 538.3700578433744
stock price yesterday 542.729945404414
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  59
stock price today 533.1484615041092
stock price yesterday 538.3700578433744
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  60
stock price today 527.1824221833044
stock price yesterday 533.1484615041092
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  61
stock price today 520.6059242620878
stock price yesterday 527.1824221833044
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  62
stock price today 513.5666617056817
stock price yesterday 520.6059242620878
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  63
stock price today 506.2227211753532
stock price yesterday 513.5666617056817
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  64
stock price today 498.7390317428171
stock price yesterday 506.2227211753532
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  65
stock price today 491.283660938851
stock price yesterday 498.7390317428171
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  66
stock price today 484.0240403188863
stock price yesterday 491.283660938851
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  67
stock price today 477.12320531123396
stock price yesterday 484.0240403188863
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  68
stock price today 470.73613379284825
stock price yesterday 477.12320531123396
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  69
stock price today 465.0062656203229
stock price yesterday 470.73613379284825
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  70
stock price today 460.06228127994996
stock price yesterday 465.0062656203229
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  71
stock price today 456.0152120014165
stock price yesterday 460.06228127994996
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  72
stock price today 452.9559462357546
stock price yesterday 456.0152120014165
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  73
stock price today 450.95318849667547
stock price yesterday 452.9559462357546
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  74
stock price today 450.05191640530916
stock price yesterday 450.95318849667547
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  75
stock price today 450.2723705898005
stock price yesterday 450.05191640530916
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [0, 1]
day:  76
stock price today 451.60960012443695
stock price yesterday 450.2723705898005
portfolio_value 1346.9144186800715
old_allocation [0, 1]
allocation: [0, 1]
day:  77
stock price today 454.0335737167662
stock price yesterday 451.60960012443695
portfolio_value 1354.1438597307233
old_allocation [0, 1]
allocation: [0, 1]
day:  78
stock price today 457.48985414568165
stock price yesterday 454.0335737167662
portfolio_value 1364.4521302888008
old_allocation [0, 1]
allocation: [0, 1]
day:  79
stock price today 461.90082080404835
stock price yesterday 457.48985414568165
portfolio_value 1377.6077288208828
old_allocation [0, 1]
allocation: [0, 1]
day:  80
stock price today 467.1674128901992
stock price yesterday 461.90082080404835
portfolio_value 1393.315208945726
old_allocation [0, 1]
allocation: [0, 1]
day:  81
stock price today 473.17135409997826
stock price yesterday 467.1674128901992
portfolio_value 1411.2218145230447
old_allocation [0, 1]
allocation: [0, 1]
day:  82
stock price today 479.777808857543
stock price yesterday 473.17135409997826
portfolio_value 1430.9254017959229
old_allocation [0, 1]
allocation: [0, 1]
day:  83
stock price today 486.83841043170986
stock price yesterday 479.777808857543
portfolio_value 1451.9834706726256
old_allocation [0, 1]
allocation: [0, 1]
day:  84
stock price today 494.1945929328771
stock price yesterday 486.83841043170986
portfolio_value 1473.9231023246855
old_allocation [0, 1]
allocation: [0, 1]
day:  85
stock price today 501.68115236105683
stock price yesterday 494.1945929328771
portfolio_value 1496.2515799242362
old_allocation [0, 1]
allocation: [0, 1]
day:  86
stock price today 509.1299567315567
stock price yesterday 501.68115236105683
portfolio_value 1518.4674540017336
old_allocation [0, 1]
allocation: [0, 1]
day:  87
stock price today 516.3737219568847
stock price yesterday 509.1299567315567
portfolio_value 1540.0718039199794
old_allocation [0, 1]
allocation: [0, 1]
day:  88
stock price today 523.249768686711
stock price yesterday 516.3737219568847
portfolio_value 1560.5794425560252
old_allocation [0, 1]
allocation: [0, 1]
day:  89
stock price today 529.6036757353611
stock price yesterday 523.249768686711
portfolio_value 1579.529812557951
old_allocation [0, 1]
allocation: [0, 1]
day:  90
stock price today 535.2927480487332
stock price yesterday 529.6036757353611
portfolio_value 1596.497329470087
old_allocation [0, 1]
allocation: [0, 1]
day:  91
stock price today 540.1892213275811
stock price yesterday 535.2927480487332
portfolio_value 1611.1009394423832
old_allocation [0, 1]
allocation: [0, 1]
day:  92
stock price today 544.1831313382318
stock price yesterday 540.1892213275811
portfolio_value 1623.0126768783762
old_allocation [0, 1]
allocation: [0, 1]
day:  93
stock price today 547.1847834722053
stock price yesterday 544.1831313382318
portfolio_value 1631.9650298354363
old_allocation [0, 1]
allocation: [0, 1]
day:  94
stock price today 549.1267670937505
stock price yesterday 547.1847834722053
portfolio_value 1637.7569477662753
old_allocation [0, 1]
allocation: [0, 1]
day:  95
stock price today 549.9654694373959
stock price yesterday 549.1267670937505
portfolio_value 1640.2583566808014
old_allocation [0, 1]
allocation: [0, 1]
day:  96
stock price today 549.6820550566381
stock price yesterday 549.9654694373959
portfolio_value 1639.4130803275114
old_allocation [0, 1]
allocation: [1, 0]
day:  97
stock price today 548.2828888274639
stock price yesterday 549.6820550566381
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  98
stock price today 545.799393006957
stock price yesterday 548.2828888274639
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  99
stock price today 542.2873415571468
stock price yesterday 545.799393006957
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  100
stock price today 537.825607582062
stock price yesterday 542.2873415571468
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  101
stock price today 532.5143920078558
stock price yesterday 537.825607582062
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  102
stock price today 526.4729732860233
stock price yesterday 532.5143920078558
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  103
stock price today 519.8370286565307
stock price yesterday 526.4729732860233
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  104
stock price today 512.7555871295087
stock price yesterday 519.8370286565307
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  105
stock price today 505.3876826149722
stock price yesterday 512.7555871295087
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  106
stock price today 497.898782364058
stock price yesterday 505.3876826149722
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  107
stock price today 490.4570709312906
stock price yesterday 497.898782364058
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  108
stock price today 483.2296731120719
stock price yesterday 490.4570709312906
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  109
stock price today 476.3789006800767
stock price yesterday 483.2296731120719
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  110
stock price today 470.0586072147383
stock price yesterday 476.3789006800767
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  111
stock price today 464.4107328815438
stock price yesterday 470.0586072147383
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  112
stock price today 459.56211676192254
stock price yesterday 464.4107328815438
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  113
stock price today 455.62164832092475
stock price yesterday 459.56211676192254
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  114
stock price today 452.67782198458957
stock price yesterday 455.62164832092475
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  115
stock price today 450.79674974591785
stock price yesterday 452.67782198458957
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  116
stock price today 450.0206764320391
stock price yesterday 450.79674974591785
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  117
stock price today 450.36703097646836
stock price yesterday 450.0206764320391
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [0, 1]
day:  118
stock price today 451.8280350028337
stock price yesterday 450.36703097646836
portfolio_value 1644.7313850578585
old_allocation [0, 1]
allocation: [0, 1]
day:  119
stock price today 454.3708775104408
stock price yesterday 451.8280350028337
portfolio_value 1653.9877670340109
old_allocation [0, 1]
allocation: [0, 1]
day:  120
stock price today 457.9384517386119
stock price yesterday 454.3708775104408
portfolio_value 1666.9743478723594
old_allocation [0, 1]
allocation: [0, 1]
day:  121
stock price today 462.4506376614162
stock price yesterday 457.9384517386119
portfolio_value 1683.399476964683
old_allocation [0, 1]
allocation: [0, 1]
day:  122
stock price today 467.8061013107229
stock price yesterday 462.4506376614162
portfolio_value 1702.8942813220444
old_allocation [0, 1]
allocation: [0, 1]
day:  123
stock price today 473.8845705186634
stock price yesterday 467.8061013107229
portfolio_value 1725.0209496668822
old_allocation [0, 1]
allocation: [0, 1]
day:  124
stock price today 480.5495359712292
stock price yesterday 473.8845705186634
portfolio_value 1749.2825647304376
old_allocation [0, 1]
allocation: [0, 1]
day:  125
stock price today 487.6513169131688

In [19]:
optimal_periodic_df

     day allocation_weights  new_portfolio_value
0      1         [0.5, 0.5]          1000.000000
1      2             [0, 1]          1014.943813
2      3             [0, 1]          1029.552021
3      4             [0, 1]          1043.496553
4      5             [0, 1]          1056.464247
..   ...                ...                  ...
985  986             [1, 0]        105289.941146
986  987             [1, 0]        105289.941146
987  988             [1, 0]        105289.941146
988  989             [1, 0]        105289.941146
989  990             [1, 0]        105289.941146

[990 rows x 3 columns]

I clean the allocation weights column so that is always a list of two numbers, and the portfolio is always a float with two decimal digits:

In [20]:
def clean_allocation_df(df):
    allocation_column = df.filter(regex = 'allocation').columns[0]
    portfolio_column = df.filter(regex = 'portfolio').columns[0]
    # Convert allocation_weights to [1, 0] or [0, 1] format
    # Convert allocation_weights to list of two floats with two decimal digits
    if df[allocation_column].dtype == object:
        df[allocation_column] = df[allocation_column].apply(
            lambda x: [round(float(i.strip()), 2) for i in str(x).strip("[]").split(",")]
        )


    # Clean and convert new_portfolio_value to float with 2 decimals
    df[portfolio_column] = (
        df[portfolio_column]
        .astype(str)                      # ensure string for cleanup
        .str.replace(",", "", regex=False)  # remove thousand separators
        .astype(float)
        .round(2)
    )

    return df

optimal_upward_df = clean_allocation_df(optimal_upward_df)
optimal_periodic_df = clean_allocation_df(optimal_periodic_df)
optimal_downward_df = clean_allocation_df(optimal_downward_df)

In [21]:
optimal_upward_df.head()

        day allocation_weights  new_portfolio_value
498501    1         [0.5, 0.5]               1005.0
498502    2         [0.0, 1.0]               1015.0
498503    3         [0.0, 1.0]               1025.0
498504    4         [0.0, 1.0]               1035.0
498505    5         [0.0, 1.0]               1045.0

In [22]:
optimal_downward_df.head()

        day allocation_weights  new_portfolio_value
498501    1         [0.5, 0.5]               1000.0
498502    2         [1.0, 0.0]               1000.0
498503    3         [1.0, 0.0]               1000.0
498504    4         [1.0, 0.0]               1000.0
498505    5         [1.0, 0.0]               1000.0

In [23]:
optimal_periodic_df.head()

   day allocation_weights  new_portfolio_value
0    1         [0.5, 0.5]              1000.00
1    2         [0.0, 1.0]              1014.94
2    3         [0.0, 1.0]              1029.55
3    4         [0.0, 1.0]              1043.50
4    5         [0.0, 1.0]              1056.46

Now I can compute the Mean allocation error and the difference of the final portfolio value between each single run and the optimal baseline (according to the right generator associated to the run):

In [24]:
base_path = "Results/4_1"
base_path_noisy = "Results/4_2"
agents = ["a2c", "ddpg"]
regimes = ["upward", "downward", "periodic", "upward_noise", "downward_noise", "periodic_noise"]

# Result containers
result_dfs = {}  # structure: result_dfs[agent][regime]
all_data = {}

# Function to compute mean L2 error
def compute_mean_l2_error(agent_allocs, opt_allocs):
    errors = np.linalg.norm(agent_allocs - opt_allocs, axis=1)
    return np.mean(errors)

# You must define or load the optimal allocation DataFrames for each regime
optimal_data = {
    "upward": clean_allocation_df(optimal_upward_df),
    "downward": clean_allocation_df(optimal_downward_df),
    "periodic": clean_allocation_df(optimal_periodic_df),
     "upward_noise": clean_allocation_df(optimal_upward_df),
    "downward_noise": clean_allocation_df(optimal_downward_df),
    "periodic_noise": clean_allocation_df(optimal_periodic_df),
}

for agent in agents:
    result_dfs[agent] = {}
    all_data[agent] = {}
    
    for regime in regimes:
        # Prepare optimal allocations
        opt_allocs_array = np.array(optimal_data[regime]["allocation_weights"].tolist())

        # Gather CSVs
        # Select correct base path based on regime type
        current_base = base_path_noisy if "noise" in regime else base_path
        csv_pattern = os.path.join(current_base, agent, regime, "training_logs", "*.csv")

        csv_files = sorted(glob.glob(csv_pattern))
        print(csv_files)
        mean_errors = []
        dfs = []
        delta_vs = []

        for fpath in csv_files:
            df = pd.read_csv(fpath)
            df = clean_allocation_df(df.loc[df['episode'] == 50, ['day',"allocation_weights", 'new_portfolio_value']])
            agent_allocs_array = np.array(df["allocation_weights"].tolist())
            min_len = min(len(agent_allocs_array), len(opt_allocs_array))
            opt_df = optimal_data[regime]
            if (agent == 'a2c') and (regime == "downward_noise"):
                agent_allocs_array_check = agent_allocs_array
                opt_allocs_array_check = opt_allocs_array

            error = compute_mean_l2_error(agent_allocs_array[:min_len], opt_allocs_array[:min_len])
            mean_errors.append(error)
            dfs.append(df)
              # Compute ∆V
            try:
                V_agent_T = float(str(df["new_portfolio_value"].iloc[-1]).replace(",", ""))
                V_opt_T = float(str(opt_df["new_portfolio_value"].iloc[min_len - 1]).replace(",", ""))
                delta_v = V_agent_T - V_opt_T
            except Exception as e:
                delta_v = np.nan  # fallback if any issue
            delta_vs.append(delta_v)

        result_dfs[agent][regime] = pd.DataFrame({
            "run": list(range(1, len(mean_errors) + 1)),
            "mean_allocation_error": mean_errors,
            "delta_V": delta_vs
        })
        all_data[agent][regime] = pd.concat(dfs, ignore_index=True)

['Results/4_1/a2c/upward/training_logs/01.csv', 'Results/4_1/a2c/upward/training_logs/02.csv', 'Results/4_1/a2c/upward/training_logs/03.csv', 'Results/4_1/a2c/upward/training_logs/04.csv', 'Results/4_1/a2c/upward/training_logs/05.csv', 'Results/4_1/a2c/upward/training_logs/06.csv', 'Results/4_1/a2c/upward/training_logs/07.csv', 'Results/4_1/a2c/upward/training_logs/08.csv', 'Results/4_1/a2c/upward/training_logs/09.csv', 'Results/4_1/a2c/upward/training_logs/10.csv']
['Results/4_1/a2c/downward/training_logs/01.csv', 'Results/4_1/a2c/downward/training_logs/02.csv', 'Results/4_1/a2c/downward/training_logs/03.csv', 'Results/4_1/a2c/downward/training_logs/04.csv', 'Results/4_1/a2c/downward/training_logs/05.csv', 'Results/4_1/a2c/downward/training_logs/06.csv', 'Results/4_1/a2c/downward/training_logs/07.csv', 'Results/4_1/a2c/downward/training_logs/08.csv', 'Results/4_1/a2c/downward/training_logs/09.csv', 'Results/4_1/a2c/downward/training_logs/10.csv']
['Results/4_1/a2c/periodic/training_logs/01.csv', 'Results/4_1/a2c/periodic/training_logs/02.csv', 'Results/4_1/a2c/periodic/training_logs/03.csv', 'Results/4_1/a2c/periodic/training_logs/04.csv', 'Results/4_1/a2c/periodic/training_logs/05.csv', 'Results/4_1/a2c/periodic/training_logs/06.csv', 'Results/4_1/a2c/periodic/training_logs/07.csv', 'Results/4_1/a2c/periodic/training_logs/08.csv', 'Results/4_1/a2c/periodic/training_logs/09.csv', 'Results/4_1/a2c/periodic/training_logs/10.csv']
['Results/4_2/a2c/upward_noise/training_logs/01.csv', 'Results/4_2/a2c/upward_noise/training_logs/02.csv', 'Results/4_2/a2c/upward_noise/training_logs/03.csv', 'Results/4_2/a2c/upward_noise/training_logs/04.csv', 'Results/4_2/a2c/upward_noise/training_logs/05.csv', 'Results/4_2/a2c/upward_noise/training_logs/06.csv', 'Results/4_2/a2c/upward_noise/training_logs/07.csv', 'Results/4_2/a2c/upward_noise/training_logs/08.csv', 'Results/4_2/a2c/upward_noise/training_logs/09.csv', 'Results/4_2/a2c/upward_noise/training_logs/10.csv']
['Results/4_2/a2c/downward_noise/training_logs/01.csv', 'Results/4_2/a2c/downward_noise/training_logs/02.csv', 'Results/4_2/a2c/downward_noise/training_logs/03.csv', 'Results/4_2/a2c/downward_noise/training_logs/04.csv', 'Results/4_2/a2c/downward_noise/training_logs/05.csv', 'Results/4_2/a2c/downward_noise/training_logs/06.csv', 'Results/4_2/a2c/downward_noise/training_logs/07.csv', 'Results/4_2/a2c/downward_noise/training_logs/08.csv', 'Results/4_2/a2c/downward_noise/training_logs/09.csv', 'Results/4_2/a2c/downward_noise/training_logs/10.csv']
['Results/4_2/a2c/periodic_noise/training_logs/01.csv', 'Results/4_2/a2c/periodic_noise/training_logs/02.csv', 'Results/4_2/a2c/periodic_noise/training_logs/03.csv', 'Results/4_2/a2c/periodic_noise/training_logs/04.csv', 'Results/4_2/a2c/periodic_noise/training_logs/05.csv', 'Results/4_2/a2c/periodic_noise/training_logs/06.csv', 'Results/4_2/a2c/periodic_noise/training_logs/07.csv', 'Results/4_2/a2c/periodic_noise/training_logs/08.csv', 'Results/4_2/a2c/periodic_noise/training_logs/09.csv', 'Results/4_2/a2c/periodic_noise/training_logs/10.csv']
['Results/4_1/ddpg/upward/training_logs/01.csv', 'Results/4_1/ddpg/upward/training_logs/02.csv', 'Results/4_1/ddpg/upward/training_logs/03.csv', 'Results/4_1/ddpg/upward/training_logs/04.csv', 'Results/4_1/ddpg/upward/training_logs/05.csv', 'Results/4_1/ddpg/upward/training_logs/06.csv', 'Results/4_1/ddpg/upward/training_logs/07.csv', 'Results/4_1/ddpg/upward/training_logs/08.csv', 'Results/4_1/ddpg/upward/training_logs/09.csv', 'Results/4_1/ddpg/upward/training_logs/10.csv']
['Results/4_1/ddpg/downward/training_logs/01.csv', 'Results/4_1/ddpg/downward/training_logs/02.csv', 'Results/4_1/ddpg/downward/training_logs/03.csv', 'Results/4_1/ddpg/downward/training_logs/04.csv', 'Results/4_1/ddpg/downward/training_logs/05.csv', 'Results/4_1/ddpg/downward/training_logs/06.csv', 'Results/4_1/ddpg/downward/training_logs/07.csv', 'Results/4_1/ddpg/downward/training_logs/08.csv', 'Results/4_1/ddpg/downward/training_logs/09.csv', 'Results/4_1/ddpg/downward/training_logs/10.csv']
['Results/4_1/ddpg/periodic/training_logs/01.csv', 'Results/4_1/ddpg/periodic/training_logs/02.csv', 'Results/4_1/ddpg/periodic/training_logs/03.csv', 'Results/4_1/ddpg/periodic/training_logs/04.csv', 'Results/4_1/ddpg/periodic/training_logs/05.csv', 'Results/4_1/ddpg/periodic/training_logs/06.csv', 'Results/4_1/ddpg/periodic/training_logs/07.csv', 'Results/4_1/ddpg/periodic/training_logs/08.csv', 'Results/4_1/ddpg/periodic/training_logs/09.csv', 'Results/4_1/ddpg/periodic/training_logs/10.csv']
['Results/4_2/ddpg/upward_noise/training_logs/01.csv', 'Results/4_2/ddpg/upward_noise/training_logs/02.csv', 'Results/4_2/ddpg/upward_noise/training_logs/03.csv', 'Results/4_2/ddpg/upward_noise/training_logs/04.csv', 'Results/4_2/ddpg/upward_noise/training_logs/05.csv', 'Results/4_2/ddpg/upward_noise/training_logs/06.csv', 'Results/4_2/ddpg/upward_noise/training_logs/07.csv', 'Results/4_2/ddpg/upward_noise/training_logs/08.csv', 'Results/4_2/ddpg/upward_noise/training_logs/09.csv', 'Results/4_2/ddpg/upward_noise/training_logs/10.csv']
['Results/4_2/ddpg/downward_noise/training_logs/01.csv', 'Results/4_2/ddpg/downward_noise/training_logs/02.csv', 'Results/4_2/ddpg/downward_noise/training_logs/03.csv', 'Results/4_2/ddpg/downward_noise/training_logs/04.csv', 'Results/4_2/ddpg/downward_noise/training_logs/05.csv', 'Results/4_2/ddpg/downward_noise/training_logs/06.csv', 'Results/4_2/ddpg/downward_noise/training_logs/07.csv', 'Results/4_2/ddpg/downward_noise/training_logs/08.csv', 'Results/4_2/ddpg/downward_noise/training_logs/09.csv', 'Results/4_2/ddpg/downward_noise/training_logs/10.csv']
['Results/4_2/ddpg/periodic_noise/training_logs/01.csv', 'Results/4_2/ddpg/periodic_noise/training_logs/02.csv', 'Results/4_2/ddpg/periodic_noise/training_logs/03.csv', 'Results/4_2/ddpg/periodic_noise/training_logs/04.csv', 'Results/4_2/ddpg/periodic_noise/training_logs/05.csv', 'Results/4_2/ddpg/periodic_noise/training_logs/06.csv', 'Results/4_2/ddpg/periodic_noise/training_logs/07.csv', 'Results/4_2/ddpg/periodic_noise/training_logs/08.csv', 'Results/4_2/ddpg/periodic_noise/training_logs/09.csv', 'Results/4_2/ddpg/periodic_noise/training_logs/10.csv']

This is to access the mean allocation error and the delta V for each run after choosing an agent and a generator:

In [25]:
result_dfs['a2c']['periodic']

   run  mean_allocation_error    delta_V
0    1               0.709964 -104378.94
1    2               0.710149 -104383.94
2    3               0.710278 -104377.94
3    4               0.707192 -104363.94
4    5               0.709921 -104377.94
5    6               0.710507 -104379.94
6    7               0.709935 -104377.94
7    8               0.708592 -104372.94
8    9               0.708107 -104369.94
9   10               0.712107 -104387.94

Generate the LATEX table:

In [28]:
for agent in ["a2c", "ddpg"]:
    print("\\begin{table}[ht]")
    print("  \\centering")
    print(f"  \\caption{{Expt. 1\&2 - {agent.upper()} Results Averaged Across 10 Runs with Different Generators}}")
    print(f"  \\label{{tab:{agent}_results}}")

    # --- Clean Regimes Subtable ---
    print("  \\begin{subtable}[t]{0.48\\textwidth}")
    print("  \\centering")
    print("  \\caption{Generators with no Noise}")
    print("  \\begin{tabular}{ccc}")
    print("  \\toprule")
    print("  Generator & Mean Allocation Error & $\\Delta V$ \\\\")
    print("  \\midrule")
    for regime in ["upward", "downward", "periodic"]:
        df = result_dfs[agent].get(regime)
        if df is not None and not df.empty:
            mean_error = df["mean_allocation_error"].mean() # to calculate the average Mean Allocation Error across runs
            delta_v = df["delta_V"].mean() # to calculate the average difference in final portfolio value across runs 
            print(f"  {regime.capitalize()} & {mean_error:.2f} & {delta_v:.2f} \\\\")
    print("  \\bottomrule")
    print("  \\end{tabular}")
    print("  \\end{subtable}")

    print("  \\hfill")

    # --- Noisy Regimes Subtable ---
    print("  \\begin{subtable}[t]{0.48\\textwidth}")
    print("  \\centering")
    print("  \\caption{Generators with Noise}")
    print("  \\begin{tabular}{ccc}")
    print("  \\toprule")
    print("  Generator & Mean Allocation Error & $\\Delta V$ \\\\")
    print("  \\midrule")
    for regime in ["upward_noise", "downward_noise", "periodic_noise"]:
        df = result_dfs[agent].get(regime)
        if df is not None and not df.empty:
            mean_error = df["mean_allocation_error"].mean()
            delta_v = df["delta_V"].mean()
            print(f"  {regime.replace('_noise','').capitalize()} (Noise) & {mean_error:.2f} & {delta_v:.2f} \\\\")
    print("  \\bottomrule")
    print("  \\end{tabular}")
    print("  \\end{subtable}")

    print("\\end{table}")
    print("\n\n")

\begin{table}[ht]
  \centering
  \caption{Expt. 1\&2 - A2C Results Averaged Across 10 Runs with Different Generators}
  \label{tab:a2c_results}
  \begin{subtable}[t]{0.48\textwidth}
  \centering
  \caption{Generators with no Noise}
  \begin{tabular}{ccc}
  \toprule
  Generator & Mean Allocation Error & $\Delta V$ \\
  \midrule
  Upward & 0.45 & -5395.00 \\
  Downward & 0.84 & -971.40 \\
  Periodic & 0.71 & -104377.14 \\
  \bottomrule
  \end{tabular}
  \end{subtable}
  \hfill
  \begin{subtable}[t]{0.48\textwidth}
  \centering
  \caption{Generators with Noise}
  \begin{tabular}{ccc}
  \toprule
  Generator & Mean Allocation Error & $\Delta V$ \\
  \midrule
  Upward (Noise) & 0.03 & -7072.70 \\
  Downward (Noise) & 1.40 & -464.00 \\
  Periodic (Noise) & 0.71 & -104422.04 \\
  \bottomrule
  \end{tabular}
  \end{subtable}
\end{table}



\begin{table}[ht]
  \centering
  \caption{Expt. 1\&2 - DDPG Results Averaged Across 10 Runs with Different Generators}
  \label{tab:ddpg_results}
  \begin{subtable}[t]{0.48\textwidth}
  \centering
  \caption{Generators with no Noise}
  \begin{tabular}{ccc}
  \toprule
  Generator & Mean Allocation Error & $\Delta V$ \\
  \midrule
  Upward & 0.64 & -5174.40 \\
  Downward & 0.64 & -774.70 \\
  Periodic & 0.71 & -104323.74 \\
  \bottomrule
  \end{tabular}
  \end{subtable}
  \hfill
  \begin{subtable}[t]{0.48\textwidth}
  \centering
  \caption{Generators with Noise}
  \begin{tabular}{ccc}
  \toprule
  Generator & Mean Allocation Error & $\Delta V$ \\
  \midrule
  Upward (Noise) & 0.71 & -8531.10 \\
  Downward (Noise) & 0.85 & -278.60 \\
  Periodic (Noise) & 0.71 & -104262.34 \\
  \bottomrule
  \end{tabular}
  \end{subtable}
\end{table}