In [1]:
import pandas as pd
import numpy as np
import pickle
pd.set_option("display.width", 1000)
pd.set_option("display.max_columns", None)

In [2]:

def evaluate_portfolio(w, returns):
    daily_ret = returns @ w
    ann_return = daily_ret.mean() * 252
    ann_vol = daily_ret.std() * np.sqrt(252)
    sharpe = ann_return / ann_vol if ann_vol > 0 else np.nan
    return ann_return, ann_vol, sharpe

In [3]:
def build_efficiency_table(
    results,
    returns_is,
    returns_oos,
    vol_levels
):
    rows = []

    # --- ESG portfolios ---
    for vol in vol_levels:
        # closest model-implied volatility
        vols = np.array([r["Volatility"] for r in results])
        idx = np.argmin(np.abs(vols - vol))
        w = results[idx]["Weights"]

        is_metrics  = evaluate_portfolio(w, returns_is)
        oos_metrics = evaluate_portfolio(w, returns_oos)

        rows.append({
            "Volatility Target": vol,
            "Return (IS)": is_metrics[0],
            "Return (OOS)": oos_metrics[0],
            "Volatility (OOS)": oos_metrics[1],
            "Sharpe (IS)": is_metrics[2],
            "Sharpe (OOS)": oos_metrics[2],
        })

 

    return pd.DataFrame(rows)

In [5]:
returns_oos = pd.read_parquet("data/returns_oos_2024.parquet")
returns_is_5y = pd.read_parquet("data/returns_5y.parquet")
returns_is_10y =  pd.read_parquet("data/returns_10y.parquet")

In [8]:
with open("results/optimized_weights_10y.pkl", "rb") as f:
    results_10y = pickle.load(f)

with open("results/optimized_weights_5y.pkl", "rb") as f:
    results_5y = pickle.load(f)

In [9]:
results_10y

[{'Volatility': 0.16000000488789265,
  'ESG': 85.89803005335574,
  'Weights': array([2.64276311e-09, 7.02361831e-09, 1.27933073e-08, 2.36526569e-08,
         9.09673129e-10, 1.65484047e-09, 2.59000728e-09, 4.47674553e-01,
         7.49974948e-09, 2.26299456e-09, 1.94465727e-09, 2.84717807e-01,
         1.73575398e-08, 1.15345311e-01, 5.93769698e-10, 1.71182139e-09,
         4.56687691e-09, 4.17222610e-09, 1.52262238e-01])},
 {'Volatility': 0.1700000203993497,
  'ESG': 86.85440270961296,
  'Weights': array([ 6.96996593e-09,  1.90462139e-08,  3.86181246e-08,  5.49331872e-08,
          8.94428550e-10,  3.23298221e-09,  5.67022215e-09,  4.42590937e-01,
          1.99448763e-08,  3.66700520e-09,  2.83473255e-09,  3.72598197e-01,
          2.54877954e-08,  1.54173123e-01, -5.84557601e-10,  2.68314190e-09,
          1.19476053e-08,  6.72234131e-09,  3.06375390e-02])},
 {'Volatility': 0.1800000001689806,
  'ESG': 87.48763772320267,
  'Weights': array([ 3.62487411e-11,  1.03220421e-10,  2.19036784e-10,  2.97882061e-10,
         -2.10188746e-12,  1.22750434e-11,  2.56718638e-11,  3.30382915e-01,
          1.09909760e-10,  1.16160635e-11,  7.08653991e-12,  4.89306318e-01,
          1.18262409e-10,  1.80310765e-01, -1.16974941e-11,  7.16206045e-12,
          6.29194122e-11,  2.59009640e-11,  5.40017619e-10])},
 {'Volatility': 0.19000000619391313,
  'ESG': 87.90782822178507,
  'Weights': array([ 1.11410343e-09,  3.54543958e-09,  7.70954147e-09,  1.05027396e-08,
         -3.09259570e-10,  2.27352823e-10,  6.92768719e-10,  2.11580624e-01,
          3.75125842e-09,  1.46720695e-10, -1.20372734e-11,  5.90603866e-01,
          3.75199880e-09,  1.97815465e-01, -6.68666980e-10,  8.85870193e-12,
          2.07309695e-09,  5.97701107e-10,  1.18328949e-08])},
 {'Volatility': 0.20000000805518145,
  'ESG': 88.25169273167089,
  'Weights': array([ 1.43868679e-09,  4.78762764e-09,  1.06709351e-08,  1.47238741e-08,
         -6.01200505e-10,  1.80860488e-10,  8.13319880e-10,  1.14357730e-01,
          5.17371785e-09,  5.36383001e-12, -2.14036706e-10,  6.73500061e-01,
          4.86458507e-09,  2.12142151e-01, -1.15816455e-09, -1.66043510e-10,
          2.73759142e-09,  5.99574480e-10,  1.40031048e-08])},
 {'Volatility': 0.21000000630069082,
  'ESG': 88.55558161407376,
  'Weights': array([ 1.04428076e-09,  3.51593177e-09,  8.82287006e-09,  1.23717658e-08,
         -1.00347135e-09, -2.19487852e-10,  2.79447780e-10,  2.84169400e-02,
          4.34621949e-09, -5.87686320e-10, -7.58635183e-10,  7.46727006e-01,
          3.04930070e-09,  2.24856016e-01, -1.65564157e-09, -6.72660361e-10,
          1.90740618e-09, -1.59443380e-10,  7.45774146e-09])},
 {'Volatility': 0.22000000045509338,
  'ESG': 88.79608198144246,
  'Weights': array([ 8.26801376e-11,  3.01574364e-10,  7.54957502e-10,  1.11975099e-09,
         -7.60211529e-11, -1.86550937e-11,  2.72141005e-11,  6.21431164e-09,
          3.39742674e-10, -3.42866274e-11, -4.91832725e-11,  8.66739461e-01,
          2.83634939e-10,  1.33260529e-01, -1.12565650e-10, -4.54517006e-11,
          1.68126538e-10,  4.69117188e-12,  6.83677529e-10])},
 {'Volatility': 0.23000000144705088,
  'ESG': 88.94517433707018,
  'Weights': array([ 4.96784145e-10,  2.07335693e-09,  5.73310728e-09,  8.83896269e-09,
         -8.54281190e-10, -3.48818085e-10, -4.62380208e-12,  3.37109682e-08,
          2.57013215e-09, -5.58695120e-10, -6.72756587e-10,  9.68748176e-01,
          1.81120469e-09,  3.12517674e-02, -1.20696087e-09, -6.23050259e-10,
          1.08245403e-09, -2.70455743e-10,  4.43156735e-09])},
 {'Volatility': 0.23364498673465406,
  'ESG': 88.99085115771291,
  'Weights': array([-1.86939683e-12, -1.92117619e-12, -7.62584164e-13,  8.77951344e-13,
         -2.43386611e-12, -1.90685345e-12, -2.01818075e-12, -1.15784750e-12,
         -7.92787245e-13, -2.59588422e-12, -2.62937631e-12,  1.00000000e+00,
         -2.38675555e-12, -5.36492677e-12, -2.88342735e-12, -2.43764472e-12,
         -2.01951888e-12, -2.62621860e-12, -2.47577964e-12])},
 {'Volatility': 0.2336449867298055,
  'ESG': 88.99085115721982,
  'Weights': array([-2.61121028e-14, -2.38732575e-14,  1.11776708e-14,  6.21772050e-14,
         -4.15374580e-14, -3.05804371e-14, -3.08123090e-14,  1.04787224e-15,
         -1.13331539e-15, -4.27610338e-14, -4.38069791e-14,  1.00000000e+00,
         -3.35657751e-14, -1.14424352e-13, -5.05047097e-14, -4.04047155e-14,
         -2.73846192e-14, -4.21364988e-14, -3.42804760e-14])},
 {'Volatility': 0.23364498584412938,
  'ESG': 88.99085142727083,
  'Weights': array([-1.39432239e-09, -1.12719721e-09,  1.42441686e-09,  5.04979374e-09,
         -2.39758618e-09, -1.74342132e-09, -1.70171248e-09,  4.95381390e-09,
          1.09842121e-10, -2.39503263e-09, -2.47284407e-09,  9.99999990e-01,
         -1.65998430e-09,  2.25788940e-08, -2.93795136e-09, -2.28932768e-09,
         -1.40296740e-09, -2.31192487e-09, -1.41783906e-09])},
 {'Volatility': 0.23364498645307,
  'ESG': 88.99085128529673,
  'Weights': array([-6.89641461e-10, -7.03836008e-10,  2.47308422e-10,  1.82106163e-09,
         -1.01401601e-09, -7.63820242e-10, -7.74439071e-10,  2.05538505e-09,
         -2.26387011e-10, -1.02867848e-09, -1.05667466e-09,  9.99999996e-01,
         -9.02053019e-10,  1.08448844e-08, -1.23197966e-09, -9.79634729e-10,
         -7.40983279e-10, -1.01128613e-09, -9.41492938e-10])},
 {'Volatility': 0.2336449865400508,
  'ESG': 88.99085121237938,
  'Weights': array([-3.20887548e-10, -3.86693975e-10, -3.92889554e-11,  6.61148774e-10,
         -4.12700078e-10, -3.21769697e-10, -3.37271835e-10,  9.57729366e-10,
         -2.14130925e-10, -4.23441003e-10, -4.33124859e-10,  9.99999998e-01,
         -4.54873893e-10,  5.73220839e-09, -4.98424452e-10, -4.02439664e-10,
         -3.64167095e-10, -4.22990247e-10, -5.42406589e-10])},
 {'Volatility': 0.2336449867644856,
  'ESG': 88.9908511601659,
  'Weights': array([-1.35129637e-11, -1.86764072e-11, -1.27809043e-11,  5.68230357e-12,
         -1.35600564e-11, -1.14229052e-11, -1.28780988e-11, -3.37675595e-12,
         -1.40733094e-11, -1.47303535e-11, -1.48227939e-11,  1.00000000e+00,
         -2.03803423e-11, -4.08621963e-11, -1.59416380e-11, -1.37784408e-11,
         -1.61744732e-11, -1.53965870e-11, -2.63142938e-11])},
 {'Volatility': 0.23364498673289774,
  'ESG': 88.99085115747376,
  'Weights': array([-1.23062538e-12, -1.87651822e-12, -1.37444792e-12,  6.28549258e-13,
         -1.17660183e-12, -1.01251446e-12, -1.15789656e-12,  4.02037836e-13,
         -1.54974288e-12, -1.27809451e-12, -1.28376817e-12,  1.00000000e+00,
         -1.99086934e-12, -3.90394146e-12, -1.39631109e-12, -1.19943946e-12,
         -1.54222180e-12, -1.34522593e-12, -2.74794256e-12])},
 {'Volatility': 0.2336449867356444,
  'ESG': 88.99085115767059,
  'Weights': array([-2.23774429e-12, -3.89545193e-12, -2.73938918e-12,  2.60147543e-12,
         -2.27015142e-12, -1.92329132e-12, -2.16311191e-12,  3.18146964e-12,
         -3.35460480e-12, -2.38493936e-12, -2.41032709e-12,  1.00000000e+00,
         -4.06581421e-12, -8.91211338e-12, -2.76682182e-12, -2.27105002e-12,
         -2.99343946e-12, -2.47562157e-12, -6.25217004e-12])},
 {'Volatility': 0.2336449867333841,
  'ESG': 88.99085115748547,
  'Weights': array([-1.33911016e-12, -2.40593740e-12, -1.83790134e-12,  1.42287078e-12,
         -1.36116200e-12, -1.13953784e-12, -1.28001707e-12,  1.82741869e-12,
         -2.12577658e-12, -1.41519987e-12, -1.43586315e-12,  1.00000000e+00,
         -2.48178296e-12, -5.57056925e-12, -1.67039543e-12, -1.35309068e-12,
         -1.81007094e-12, -1.46184320e-12, -3.94319585e-12])},
 {'Volatility': 0.2336449867321546,
  'ESG': 88.99085115738862,
  'Weights': array([-8.66329516e-13, -1.58706982e-12, -1.30382319e-12,  8.08515343e-13,
         -8.82375327e-13, -7.29998564e-13, -8.17753592e-13,  1.11571861e-12,
         -1.43494508e-12, -9.07740116e-13, -9.24797697e-13,  1.00000000e+00,
         -1.61916633e-12, -3.71698688e-12, -1.08807622e-12, -8.71442487e-13,
         -1.17527334e-12, -9.32318327e-13, -2.63840093e-12])},
 {'Volatility': 0.23364498673138684,
  'ESG': 88.99085115732946,
  'Weights': array([-5.79651538e-13, -1.08061376e-12, -9.42648808e-13,  4.81016665e-13,
         -5.92187498e-13, -4.82562639e-13, -5.39436702e-13,  7.32426831e-13,
         -9.96595570e-13, -6.02881488e-13, -6.17024985e-13,  1.00000000e+00,
         -1.09133639e-12, -2.57616546e-12, -7.34833147e-13, -5.80766123e-13,
         -7.88439534e-13, -6.15451634e-13, -1.81990525e-12])},
 {'Volatility': 0.23364498673089532,
  'ESG': 88.99085115729311,
  'Weights': array([-4.02317111e-13, -7.55603852e-13, -6.92805365e-13,  2.92211492e-13,
         -4.12808150e-13, -3.31751498e-13, -3.69271866e-13,  5.08229878e-13,
         -7.09477995e-13, -4.15712039e-13, -4.27414632e-13,  1.00000000e+00,
         -7.55896412e-13, -1.83496411e-12, -5.14303429e-13, -4.01925102e-13,
         -5.45572659e-13, -4.21439443e-13, -1.28296801e-12])}]

In [6]:
returns_oos

Instrument   AAPL.OQ   AMGN.OQ     AXP.N      BA.N     CAT.N     CRM.N   CSCO.OQ     CVX.N     DIS.N      GS.N      HD.N    HON.OQ     IBM.N   INTC.OQ     JNJ.N     JPM.N      KO.N     MCD.N     MMM.N     MRK.N   MSFT.OQ     NKE.N      PG.N     TRV.N     UNH.N       V.N      VZ.N  WBA.OQ^H25    WMT.OQ
Date
2024-01-03 -0.007516  0.011035 -0.010624 -0.031677 -0.029152 -0.016891       0.0  0.018887  0.010309 -0.016908 -0.019961  -0.02162 -0.008707 -0.015815  0.006232 -0.004368  0.002338 -0.008961 -0.020295  0.013421 -0.000728 -0.023839 -0.006069 -0.000627  0.004975 -0.003444  0.007176   -0.041369  0.000063
2024-01-04 -0.012781  0.008214  0.004391  0.004214  0.006311 -0.002385  -0.00855 -0.011024 -0.011964  0.003034  0.000975  0.001807  0.004736 -0.003833 -0.002114  0.000467 -0.003341 -0.009042  0.003519  0.019329 -0.007203 -0.016866  0.005464  0.006461  0.006235  0.006298  0.005348   -0.052591 -0.009714
2024-01-05 -0.004021 -0.000561  0.010207   0.01644  0.009843 -0.000478    0.0002 -0.001727  0.003747  0.009072  0.012766 -0.006709 -0.010624  0.000427  0.003108  0.005005 -0.001507 -0.009471  0.003875  0.001793 -0.000517 -0.002153 -0.008309  0.002749 -0.014851  0.000308  0.020863    0.030447 -0.006678
2024-01-08  0.023887  0.025674  0.000793 -0.083731  0.011425  0.038091   0.00736 -0.006002  0.007125  0.006243  0.014446 -0.004284  0.012364  0.032728  0.002479 -0.001452  0.007347  0.010019  0.002483  0.001364  0.018696  0.014974  0.008578 -0.003944 -0.001602  0.010915 -0.002491    0.024488  0.009779
2024-01-09 -0.002266 -0.011713  -0.01298  -0.01425  0.000137    0.0018  -0.01096 -0.025747 -0.020749 -0.013254 -0.005014 -0.005095   -0.0066  -0.00829  0.000619 -0.007937 -0.001832 -0.003535  0.002202  0.008906  0.002931 -0.008529  0.004094 -0.000572  0.003442  0.003005  -0.02679    -0.01059  0.006676
...              ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...         ...       ...
2024-12-24  0.011413  0.001854  0.015475  0.009243  0.005949  0.004452  0.014643  0.006067  0.010359  0.020823  0.009359  0.007719  0.011113  0.009852  0.003985   0.01631  0.007347  0.009226  0.010643  0.000805   0.00933  0.000391  0.004925  0.006278 -0.000474  0.010755 -0.003511   -0.011898  0.025462
2024-12-26  0.003171 -0.004965  0.001745  0.005782 -0.001225 -0.007899   0.00217  0.000973 -0.000089  -0.00268 -0.002528  0.012849  0.002137  0.001959 -0.001853   0.00342 -0.004306  0.002751  0.006271  0.004214 -0.002781  0.001951  0.007196  0.003494  0.009929  0.000811  0.004012    0.051946  0.001186
2024-12-27 -0.013331 -0.002016 -0.009718  0.001883 -0.006175 -0.009615 -0.006188  0.000139 -0.008925 -0.008726 -0.005787 -0.010187 -0.009427 -0.006873 -0.003647 -0.008135  -0.00192 -0.004011 -0.007652 -0.001704 -0.017453 -0.006781 -0.003709 -0.009564 -0.002272 -0.007036 -0.001002   -0.006218 -0.012253
2024-12-30 -0.013352 -0.012837 -0.012434 -0.023345 -0.005083 -0.008039 -0.007071 -0.006479 -0.006746 -0.004575 -0.008769  -0.01276 -0.011421 -0.023929 -0.011859 -0.007701 -0.006748 -0.013786 -0.008098  -0.01343 -0.013328 -0.023434 -0.014497   -0.0064 -0.004303 -0.010568 -0.008048    -0.03814 -0.011963
2024-12-31 -0.007083  0.005154 -0.001818  0.002546 -0.000689 -0.004209  0.000169  0.012296  0.004952 -0.001623  -0.00113 -0.003138 -0.001909  0.011538   0.00889  0.001628  0.003701  0.001001  -0.00031  0.011221 -0.007869  0.013571  0.003346  0.004243 -0.003828  0.002313    0.0098    0.007531 -0.002432

[251 rows x 29 columns]

In [ ]:



def get_closest_result(results, vol_target):
    vols = np.array([r["Volatility"] for r in results])
    idx = np.argmin(np.abs(vols - vol_target))
    return results[idx]

idxes = [0, 4, 9, 14]

rows = []

for idx in idxes:
    
    # In-sample (IS)
    is_5y = evaluate_portfolio(results_5y[idx]["Weights"], returns_is_5y)
    is_10y = evaluate_portfolio(results_10y[idx]["Weights"], returns_is_10y)

    # out-of-sample (OOS) (2024)
    oos_5y = evaluate_portfolio(results_5y[idx]["Weights"], returns_oos)
    oos_10y = evaluate_portfolio(results_10y[idx]["Weights"], returns_oos)

    vol_levels = [0.16, 0.20, 0.25, 0.30]

table_5y = build_efficiency_table(
    results=results_5y,
    returns_is=returns_is_5y,
    returns_oos=returns_oos,
    vol_levels=vol_levels
)

table_10y = build_efficiency_table(
    results=results_10y,
    returns_is=returns_is_10y,
    returns_oos=returns_oos,
    vol_levels=vol_levels
)

ValueError: Dot product shape mismatch, (1259, 29) vs (19,)

In [ ]:
def build_benchmark_efficiency_table(w_is, w_oos, returns_is, returns_oos):
    is_metrics  = evaluate_portfolio(w_is, returns_is)
    oos_metrics = evaluate_portfolio(w_oos, returns_oos)

    return pd.DataFrame([{
        
        "Return (IS)": is_metrics[0],
        "Return (OOS)": oos_metrics[0],
        "Volatility (IS)": is_metrics[1],
        "Volatility (OOS)": oos_metrics[1],
        "Sharpe (IS)": is_metrics[2],
        "Sharpe (OOS)": oos_metrics[2],
    }])

In [ ]:
w_bench = pd.read_csv("data/benchmark_weights.csv").set_index("Instrument")['BenchWeight']

In [ ]:
bench_table_5y = build_benchmark_efficiency_table(
    w_is=w_bench,
    w_oos=w_bench,
    returns_is=returns_is_5y,
    returns_oos=returns_oos
)

bench_table_10y = build_benchmark_efficiency_table(
    w_is=w_bench,
    w_oos=w_bench,
    returns_is=returns_is_10y,
    returns_oos=returns_oos
)

In [ ]:
table_5y

   Volatility Target  Return (IS)  Return (OOS)  Volatility (OOS)  Sharpe (IS)  Sharpe (OOS)
0               0.16     0.036180      0.127777          0.105039     0.225335      1.216465
1               0.20    -0.012250     -0.139839          0.172062    -0.060896     -0.812725
2               0.25    -0.101288     -0.332617          0.279974    -0.402419     -1.188029
3               0.30    -0.172680     -0.728812          0.425553    -0.572701     -1.712624

In [ ]:
table_10y

   Volatility Target  Return (IS)  Return (OOS)  Volatility (OOS)  Sharpe (IS)  Sharpe (OOS)
0               0.16     0.041737      0.010543          0.137291     0.260236      0.076796
1               0.20    -0.000228     -0.207072          0.240900    -0.001133     -0.859574
2               0.25    -0.062990     -0.641336          0.398754    -0.251211     -1.608351
3               0.30    -0.078561     -1.043232          0.532634    -0.261313     -1.958627

In [ ]:
bench_table_10y

   Return (IS)  Return (OOS)  Volatility (IS)  Volatility (OOS)  Sharpe (IS)  Sharpe (OOS)
0      0.15626       0.14511         0.194557          0.116252     0.803157      1.248233

In [ ]:
bench_table_5y

   Return (IS)  Return (OOS)  Volatility (IS)  Volatility (OOS)  Sharpe (IS)  Sharpe (OOS)
0     0.185398       0.14511         0.228162          0.116252     0.812573      1.248233

In [ ]:
table_5y_fmt = table_5y.round(2)
table_10y_fmt = table_10y.round(2)
bench_table_5y_fmt = bench_table_5y.round(2)
bench_table_10y_fmt = bench_table_10y.round(2)

latex_5y = table_5y_fmt.to_latex(
    index=False,
    float_format="%.2f",
    caption="In-sample (IS) and out-of-sample (OOS) performance of ESG-optimized portfolios (5-year estimation window).",
    label="tab:efficiency_5y",
    escape=False
)
latex_5y = latex_5y.replace(
    "\\begin{tabular}",
    "\\resizebox{1\\textwidth}{!}{%\n\\begin{tabular}"
).replace(
    "\\end{tabular}",
    "\\end{tabular}\n}"
)
latex_10y = table_10y_fmt.to_latex(
    index=False,
    float_format="%.2f",
    caption="In-sample (IS) and out-of-sample (OOS) performance of ESG-optimized portfolios (10-year estimation window).",
    label="tab:efficiency_10y",
    escape=False
)
latex_10y = latex_10y.replace(
    "\\begin{tabular}",
    "\\resizebox{1\\textwidth}{!}{%\n\\begin{tabular}"
).replace(
    "\\end{tabular}",
    "\\end{tabular}\n}"
)
latex_bench_5y = bench_table_5y_fmt.to_latex(
    index=False,
    float_format="%.2f",
    caption="In-sample (IS) and out-of-sample (OOS) performance of the benchmark portfolio (5-year estimation window).",
    label="tab:efficiency_benchmark_5y",
    escape=False
)
latex_bench_5y = latex_bench_5y.replace(
    "\\begin{tabular}",
    "\\resizebox{1\\textwidth}{!}{%\n\\begin{tabular}"
).replace(
    "\\end{tabular}",
    "\\end{tabular}\n}"
)

latex_bench_10y = bench_table_10y_fmt.to_latex(
    index=False,
    float_format="%.2f",
    caption="In-sample (IS) and out-of-sample (OOS) performance of the benchmark portfolio (10-year estimation window).",
    label="tab:efficiency_benchmark_10y",
    escape=False
)
latex_bench_10y = latex_bench_10y.replace(
    "\\begin{tabular}",
    "\\resizebox{1\\textwidth}{!}{%\n\\begin{tabular}"
).replace(
    "\\end{tabular}",
    "\\end{tabular}\n}"
)

with open("results/efficiency_5y.tex", "w") as f:
    f.write(latex_5y)

with open("results/efficiency_10y.tex", "w") as f:
    f.write(latex_10y)

with open("results/efficiency_benchmark_5y.tex", "w") as f:
    f.write(latex_bench_5y)

with open("results/efficiency_benchmark_10y.tex", "w") as f:
    f.write(latex_bench_10y)