In [29]:
import pandas as pd
import pickle
import numpy as np
import matplotlib.pyplot as plt
pd.set_option("display.width", 1000)
pd.set_option("display.max_columns", None)

# Returns comparison

In [30]:
returns_10y = pd.read_parquet("data/returns_10y.parquet")
returns_5y  = pd.read_parquet("data/returns_5y.parquet")

In [31]:
mu_5y = returns_5y.mean().values.to_numpy()     
mu_10y = returns_10y.mean().values.to_numpy()

In [32]:
with open("results/optimized_weights_10y.pkl", "rb") as f:
    results_10y = pickle.load(f)

with open("results/optimized_weights_5y.pkl", "rb") as f:
    results_5y = pickle.load(f)

In [33]:
results_10y

[{'Volatility': 0.1600000055941139,
  'ESG': 86.15021703036956,
  'Weights': array([ 1.83619014e-09,  6.19814041e-09,  3.08837532e-10,  2.62564436e-09,
          4.20640798e-09,  2.42069802e-10,  1.08716531e-08,  5.75222536e-10,
          1.14742287e-09,  2.54945240e-08,  3.64113194e-10,  1.05628383e-09,
          2.08334985e-09,  2.67509474e-02,  4.20417505e-01,  6.90706534e-09,
          2.39574970e-09,  2.04120064e-09,  2.28893863e-01,  1.00422620e-07,
          8.43848889e-02,  1.30118758e-09,  1.92713658e-10,  1.39014295e-09,
          4.09019447e-09, -2.04015783e-10,  6.79355013e-09,  8.82890371e-02,
          1.51263576e-01])},
 {'Volatility': 0.1700000106740791,
  'ESG': 87.24856912010102,
  'Weights': array([ 2.64718688e-09,  7.72819444e-09,  7.98948730e-11,  4.32218175e-09,
          5.20663641e-09, -9.37007829e-11,  1.53368825e-08,  2.44053040e-10,
          8.50187203e-10,  1.96479858e-08,  1.60109708e-10,  1.10731911e-09,
          2.19623705e-09,  4.04185567e-02,  4.00262938e-01,  7.62871579e-09,
          1.64928401e-09,  1.28790456e-09,  2.83671435e-01,  1.35518143e-08,
          1.05401889e-01,  1.35845020e-09, -4.05686711e-10,  1.02793560e-09,
          4.98297832e-09, -8.32969337e-10,  3.21835557e-09,  1.40774751e-01,
          2.94703375e-02])},
 {'Volatility': 0.18000001336257446,
  'ESG': 87.97864213335689,
  'Weights': array([ 1.86922374e-09,  6.55008072e-09, -6.72853446e-10,  3.72974692e-09,
          4.21018159e-09, -8.72217508e-10,  1.37587793e-08, -5.68116115e-10,
         -3.40461225e-11,  1.68765178e-08, -6.23192406e-10,  3.01932157e-10,
          1.27153221e-09,  5.50650918e-02,  2.85297026e-01,  6.39525561e-09,
          5.86309289e-10,  2.62286510e-10,  3.51368908e-01,  9.61808161e-09,
          1.09659105e-01,  5.00355173e-10, -1.24401772e-09,  1.07230179e-10,
          3.94362573e-09, -1.60969364e-09,  1.75570047e-09,  1.98609719e-01,
          8.39530677e-08])},
 {'Volatility': 0.19000000369882483,
  'ESG': 88.47589913712999,
  'Weights': array([ 3.75708768e-10,  1.51207190e-09, -3.19182649e-10,  1.05329149e-09,
          1.01654553e-09, -3.88204469e-10,  3.57271513e-09, -3.16618281e-10,
         -1.91636479e-10,  4.71505537e-09, -3.37112853e-10, -6.92136806e-11,
          1.54761463e-10,  6.72835322e-02,  1.67398523e-01,  1.60369487e-09,
         -9.06923199e-11, -1.63956120e-10,  4.09651728e-01,  1.87439200e-09,
          1.08734987e-01, -4.05945582e-11, -5.31952959e-10, -1.73551676e-10,
          8.40065314e-10, -5.97326785e-10,  1.38921094e-10,  2.46931207e-01,
          8.86279760e-09])},
 {'Volatility': 0.20000000009820249,
  'ESG': 88.88605300678432,
  'Weights': array([-5.35026172e-11,  1.00021074e-09, -6.91022623e-10,  7.32996061e-10,
          5.62602759e-10, -7.70399472e-10,  2.88809337e-09, -7.13769176e-10,
         -6.11679591e-10,  3.58297087e-09, -7.37479918e-10, -4.68344602e-10,
         -2.91078094e-10,  7.73224022e-02,  7.01569090e-02,  1.08781034e-09,
         -5.61352929e-10, -6.24550934e-10,  4.57736532e-01,  1.04565203e-09,
          1.07980119e-01, -4.50228550e-10, -9.35914622e-10, -6.10644038e-10,
          3.61656610e-10, -9.68015058e-10, -4.09028502e-10,  2.86804033e-01,
          3.11480175e-09])},
 {'Volatility': 0.21000001314199113,
  'ESG': 89.24556226427624,
  'Weights': array([ 4.67052716e-10,  5.69588483e-09, -2.14867855e-09,  3.34376828e-09,
          3.03182956e-09, -2.47781854e-09,  1.37424115e-08, -2.14605425e-09,
         -1.72177826e-09,  1.70311084e-08, -2.26122756e-09, -1.18324424e-09,
         -3.14140212e-10,  9.07887194e-02,  6.37980387e-07,  5.52736968e-09,
         -1.30952999e-09, -1.61279192e-09,  4.95124445e-01,  6.75219216e-09,
          7.86979004e-02, -1.09507074e-09, -2.99222091e-09, -1.61741379e-09,
          2.66029429e-09, -3.23441259e-09, -4.98548457e-10,  3.35388242e-01,
          2.09837019e-08])},
 {'Volatility': 0.2200000007259689,
  'ESG': 89.48608724286251,
  'Weights': array([ 3.20448305e-11,  2.19027413e-10, -1.16367674e-10,  1.94105193e-10,
          1.59183695e-10, -1.32145932e-10,  5.91943859e-10, -1.21848738e-10,
         -9.75625838e-11,  7.76239706e-10, -1.25751247e-10, -6.58902913e-11,
         -2.78640551e-11,  8.56636560e-02,  3.21490116e-09,  2.59629888e-10,
         -8.94686914e-11, -1.02368413e-10,  4.73971155e-01,  2.05258062e-10,
          6.88804933e-08, -6.32215062e-11, -1.73369709e-10, -9.91356456e-11,
          1.01294860e-10, -1.80191983e-10, -5.69607763e-11,  4.40365115e-01,
          5.34085846e-10])},
 {'Volatility': 0.2300000000722062,
  'ESG': 89.62622525885969,
  'Weights': array([ 1.28124636e-11,  5.25022671e-11, -2.22301769e-11,  5.68673043e-11,
          4.68861519e-11, -2.69433883e-11,  1.36306451e-10, -2.41726207e-11,
         -1.83064473e-11,  1.84356346e-10, -2.52741179e-11, -9.92953244e-12,
         -1.45993979e-12,  3.88750267e-02,  4.02038464e-10,  6.77679746e-11,
         -1.77460467e-11, -2.08094715e-11,  4.13667818e-01,  4.47372980e-11,
          1.72753843e-09, -1.00189859e-11, -3.78402362e-11, -1.92852200e-11,
          2.65136891e-11, -3.89166267e-11, -1.05750850e-11,  5.47457153e-01,
          1.03942726e-10])},
 {'Volatility': 0.240000004713899,
  'ESG': 89.73282050102604,
  'Weights': array([ 5.68357044e-10,  3.50935660e-09, -2.09454678e-09,  4.04865606e-09,
          3.23378611e-09, -2.47165326e-09,  9.87688962e-09, -2.25737715e-09,
         -1.80931429e-09,  1.36666434e-08, -2.34513540e-09, -1.15661455e-09,
         -5.25689415e-10,  3.36663582e-03,  2.73185546e-08,  4.78983558e-09,
         -1.79636659e-09, -2.02793434e-09,  3.67696960e-01,  2.84579157e-09,
          1.02635606e-07, -1.17452372e-09, -3.32428970e-09, -1.89701050e-09,
          1.56485274e-09, -3.39278553e-09, -1.26297821e-09,  6.28936250e-01,
          7.11299006e-09])},
 {'Volatility': 0.25000000150032364,
  'ESG': 89.82269985689847,
  'Weights': array([ 2.19718094e-10,  1.22840540e-09, -7.06268740e-10,  1.44929161e-09,
          1.16544829e-09, -8.42271018e-10,  3.41797808e-09, -7.65913427e-10,
         -6.09329185e-10,  4.74580333e-09, -7.97124668e-10, -3.77429720e-10,
         -1.60593686e-10,  1.22241389e-06,  8.92101523e-09,  1.69195527e-09,
         -6.09774770e-10, -6.90771051e-10,  2.95806197e-01,  9.83873041e-10,
          3.09230097e-08, -3.87352787e-10, -1.14406613e-09, -6.42225336e-10,
          5.58233676e-10, -1.16575373e-09, -4.25914416e-10,  7.04192532e-01,
          2.41585934e-09])},
 {'Volatility': 0.26000000019995384,
  'ESG': 89.90141922490812,
  'Weights': array([-2.53272639e-11,  1.66593451e-10, -1.96701570e-10,  2.25079995e-10,
          1.54413952e-10, -2.21929791e-10,  6.28972067e-10, -2.08292538e-10,
         -1.79612004e-10,  9.31978239e-10, -2.14893380e-10, -1.37938180e-10,
         -9.78862431e-11,  2.19844139e-07,  1.86304655e-09,  2.70279917e-10,
         -1.81335280e-10, -1.95503627e-10,  2.29168510e-01,  1.21297368e-10,
          7.46991802e-09, -1.37720633e-10, -2.76876449e-10, -1.86031183e-10,
          4.07100659e-11, -2.79879584e-10, -1.48010951e-10,  7.70831261e-01,
          4.08250321e-10])},
 {'Volatility': 0.26999999837066935,
  'ESG': 89.97308025454916,
  'Weights': array([ 1.05669269e-11,  1.69576033e-10, -1.37029003e-10,  2.15185778e-10,
          1.68046778e-10, -1.60691679e-10,  5.13393384e-10, -1.47544487e-10,
         -1.22188974e-10,  7.30590200e-10, -1.53014475e-10, -8.37094341e-11,
         -4.96611738e-11,  6.15882472e-08,  1.28366705e-09,  2.50073840e-10,
         -1.23744986e-10, -1.36937429e-10,  1.68504859e-01,  1.27318926e-10,
          4.12546773e-09, -8.61071336e-11, -2.10307533e-10, -1.28138247e-10,
          6.40135726e-11, -2.13203157e-10, -9.45784831e-11,  8.31495073e-01,
          3.44943624e-10])},
 {'Volatility': 0.27999999995017516,
  'ESG': 90.03982687857314,
  'Weights': array([-4.13696768e-12,  8.71425618e-12, -1.60705560e-11,  1.44637248e-11,
          8.58786036e-12, -1.80248506e-11,  4.05119384e-11, -1.70345085e-11,
         -1.49840113e-11,  6.25157168e-11, -1.75676493e-11, -1.20097951e-11,
         -9.28643103e-12,  7.29225181e-09,  1.18831934e-10,  1.67926963e-11,
         -1.53848821e-11, -1.63709722e-11,  1.12001317e-01,  5.18849737e-12,
          5.66274787e-10, -1.19885333e-11, -2.20743830e-11, -1.55627597e-11,
          2.87507216e-13, -2.21683444e-11, -1.30995803e-11,  8.87998675e-01,
          2.38804730e-11])},
 {'Volatility': 0.2899999999862338,
  'ESG': 90.10293484878244,
  'Weights': array([4.62331870e-12, 6.57915825e-12, 2.78239445e-12, 7.19348219e-12,
         6.53929083e-12, 2.50056359e-12, 1.10202252e-11, 2.65158260e-12,
         2.96397801e-12, 1.38293734e-11, 2.58514255e-12, 3.43064599e-12,
         3.85262045e-12, 7.10825228e-10, 2.08971340e-11, 7.60715764e-12,
         2.93811726e-12, 2.78027634e-12, 5.85779748e-02, 6.05061660e-12,
         6.23541347e-11, 3.41008900e-12, 1.88501369e-12, 2.88795583e-12,
         5.27060857e-12, 1.85399813e-12, 3.29454946e-12, 9.41422024e-01,
         8.79369472e-12])},
 {'Volatility': 0.29999999852577164,
  'ESG': 90.16323230523518,
  'Weights': array([-2.77744212e-11,  3.35537247e-11, -9.08206233e-11,  6.16273894e-11,
          3.50874734e-11, -1.02095594e-10,  1.56802527e-10, -9.64091872e-11,
         -8.50111666e-11,  2.28985728e-10, -9.91136350e-11, -6.85419002e-11,
         -5.43085890e-11,  3.53221513e-08,  2.81774861e-10,  6.79333375e-11,
         -8.77512084e-11, -9.34928841e-11,  7.53381260e-03,  1.27398289e-11,
          1.03435817e-09, -6.94164293e-11, -1.25558541e-10, -8.86832892e-11,
         -7.73562342e-12, -1.26126358e-10, -7.53524926e-11,  9.92466151e-01,
          8.99557889e-11])},
 {'Volatility': 0.301510147895071,
  'ESG': 90.17213188687946,
  'Weights': array([-3.11705853e-12,  2.85457011e-12, -9.68310614e-12,  7.04735679e-12,
          3.91265826e-12, -1.14643105e-11,  1.33562332e-11, -1.06120794e-11,
         -9.23159438e-12,  2.04070751e-11, -1.10295492e-11, -7.23943156e-12,
         -5.83734475e-12,  1.22268528e-10,  2.55231449e-11,  6.66002414e-12,
         -9.99921234e-12, -1.07434187e-11, -2.73940336e-11,  1.47918074e-15,
          7.65152786e-11, -7.50397476e-12, -1.45728757e-11, -9.90568685e-12,
         -1.21502228e-12, -1.44950276e-11, -8.61929450e-12,  1.00000000e+00,
          6.63935878e-12])},
 {'Volatility': 0.30151014792332775,
  'ESG': 90.17213188574118,
  'Weights': array([-1.96064388e-12,  8.65222251e-15, -4.11772410e-12,  1.70928624e-12,
          3.51001865e-13, -4.77285617e-12,  4.64624049e-12, -4.45791410e-12,
         -3.97918446e-12,  8.04965499e-12, -4.64159932e-12, -3.30849111e-12,
         -2.83473205e-12,  5.39520560e-13,  9.52160829e-12,  1.67318482e-12,
         -4.28345415e-12, -4.52908212e-12, -9.40871959e-12, -8.05621177e-13,
          1.42418671e-11, -3.34436206e-12, -5.81495223e-12, -4.21643787e-12,
         -1.21508465e-12, -5.76452467e-12, -3.80780537e-12,  1.00000000e+00,
          1.87562348e-12])},
 {'Volatility': 0.30151014791812353,
  'ESG': 90.17213188482472,
  'Weights': array([-4.04029929e-13,  2.55297803e-13, -1.03408908e-12,  7.00622717e-13,
          3.32136153e-13, -1.20193421e-12,  1.45387674e-12, -1.11945933e-12,
         -9.88876782e-13,  2.23534489e-12, -1.16637814e-12, -8.03047305e-13,
         -6.64860183e-13, -2.81663373e-13,  2.24136362e-12,  7.19393061e-13,
         -1.05809562e-12, -1.12474158e-12, -2.41838881e-12,  2.44542985e-14,
          3.07839690e-12, -8.11318772e-13, -1.47786660e-12, -1.04668450e-12,
         -1.55093404e-13, -1.46848435e-12, -9.24211724e-13,  1.00000000e+00,
          7.72375506e-13])},
 {'Volatility': 0.3015101479167539,
  'ESG': 90.17213188454959,
  'Weights': array([-1.98522244e-15, -1.43696828e-15, -2.57838584e-15,  4.65749383e-17,
         -9.12113098e-16, -2.90299683e-15, -3.33198213e-16, -2.78512017e-15,
         -2.62635762e-15,  1.06895032e-15, -2.86285864e-15, -2.39502887e-15,
         -2.30855484e-15, -7.26236087e-16, -3.19589651e-15, -5.56377578e-16,
         -2.90775492e-15, -2.99407023e-15, -4.40721890e-15, -2.21231906e-15,
         -2.51154146e-15, -2.45835097e-15, -3.27705680e-15, -2.80087238e-15,
         -1.88488628e-15, -3.18583108e-15, -2.79973950e-15,  1.00000000e+00,
         -1.86682799e-15])},
 {'Volatility': 0.3015101484184192,
  'ESG': 90.17213196454465,
  'Weights': array([-1.59598701e-10, -1.16014687e-10, -1.93075159e-10,  6.79510619e-11,
         -4.95433842e-11, -2.23790367e-10,  2.15642671e-11, -2.14232222e-10,
         -2.03432643e-10,  2.37088457e-10, -2.21424684e-10, -1.86797642e-10,
         -1.85546114e-10,  9.38373612e-10, -2.63516102e-10, -1.19155172e-11,
         -2.36819468e-10, -2.43184953e-10,  6.86885825e-10, -2.10545454e-10,
          1.90068282e-10, -1.94552679e-10, -2.52594864e-10, -2.22846751e-10,
         -1.58875402e-10, -2.41612050e-10, -2.32814644e-10,  1.00000000e+00,
         -1.83579948e-10])}]

In [34]:
for r in results_5y:
    w = r["Weights"]
    r["ExpReturn"] = (mu_5y @ w) * 252

for r in results_10y:
    w = r["Weights"]
    r["ExpReturn"] = (mu_10y @ w) * 252

comparison_5y = pd.DataFrame({
    "Volatility": [r["Volatility"] for r in results_5y],
    "ESG": [r["ESG"] for r in results_5y],
    "ExpectedReturn": [r["ExpReturn"] for r in results_5y]
})

comparison_10y = pd.DataFrame({
    "Volatility": [r["Volatility"] for r in results_10y],
    "ESG": [r["ESG"] for r in results_10y],
    "ExpectedReturn": [r["ExpReturn"] for r in results_10y]
})

In [35]:
comparison_5y

    Volatility        ESG  ExpectedReturn
0     0.160000  81.577382        0.036180
1     0.170000  84.534386        0.041116
2     0.180000  86.083657        0.023036
3     0.190000  86.991575        0.006653
4     0.200000  87.645204       -0.012250
5     0.210000  88.091113       -0.028795
6     0.220000  88.456178       -0.042336
7     0.230000  88.778332       -0.054277
8     0.240000  89.073283       -0.065231
9     0.250000  89.316692       -0.101288
10    0.260000  89.496637       -0.133518
11    0.270000  89.630969       -0.147886
12    0.280000  89.732911       -0.158272
13    0.290000  89.819851       -0.167121
14    0.300000  89.896819       -0.172680
15    0.310000  89.966150       -0.177480
16    0.320000  90.030224       -0.181915
17    0.330000  90.090433       -0.186082
18    0.340000  90.147668       -0.190044
19    0.344411  90.172132       -0.191737

In [36]:
comparison_10y

    Volatility        ESG  ExpectedReturn
0      0.16000  86.150217        0.041737
1      0.17000  87.248569        0.032425
2      0.18000  87.978642        0.019884
3      0.19000  88.475899        0.008864
4      0.20000  88.886053       -0.000228
5      0.21000  89.245562       -0.014648
6      0.22000  89.486087       -0.040936
7      0.23000  89.626225       -0.050983
8      0.24000  89.732821       -0.058618
9      0.25000  89.822700       -0.062990
10     0.26000  89.901419       -0.066589
11     0.27000  89.973080       -0.069866
12     0.28000  90.039827       -0.072918
13     0.29000  90.102935       -0.075804
14     0.30000  90.163232       -0.078561
15     0.30151  90.172132       -0.078968
16     0.30151  90.172132       -0.078968
17     0.30151  90.172132       -0.078968
18     0.30151  90.172132       -0.078968
19     0.30151  90.172132       -0.078968

# Weights comparison

In [37]:
def weight_concentration(w):
    return np.sum(w**2)

for r in results_5y:
    r["Concentration"] = weight_concentration(r["Weights"])

for r in results_10y:
    r["Concentration"] = weight_concentration(r["Weights"])

In [38]:
vol_levels = [0.16, 0.20, 0.25, 0.30]

In [39]:
w_bench = pd.read_csv("data/benchmark_weights.csv")

# set Instrument as index
w_bench = w_bench.set_index("Instrument")
# keep only assets in returns (important!)
w_bench_aligned = w_bench.loc[returns_10y.columns, "BenchWeight"]

In [40]:
fig, axes = plt.subplots(2, 2, figsize=(12, 8))
axes = axes.flatten()

sigma_grid = np.linspace(0.16, 0.35, 20)
idxes =[]
for ax, vol in zip(axes, vol_levels):
    # index based on TARGET volatility
    idx = np.argmin(np.abs(sigma_grid - vol))
    idxes.append(idx)
    r5 = results_5y[idx]
    r10 = results_10y[idx]

    w5 = r5["Weights"]
    w10 = r10["Weights"]

    df = pd.DataFrame(
    {
        "5Y": w5,
        "10Y": w10
    },
    index=returns_10y.columns
)


    top = df.sort_values("10Y", ascending=False)

    x = np.arange(len(top))
    width = 0.35


    ax.bar(x - width, top["5Y"], width, label="5Y")
    ax.bar(x,          top["10Y"], width, label="10Y")


    ax.set_title(f"Target volatility ≈ {vol:.0%}")
    ax.set_xticks(x)
    ax.set_xticklabels(top.index, rotation=45, ha="right")
    ax.grid(axis="y")

    # ---- concentration annotation ONLY ----
    textstr = (
        f"Concentration (HHI):\n"
        f"5Y: {r5['Concentration']:.3f}\n"
        f"10Y: {r10['Concentration']:.3f}"
    )

    ax.text(
    0.98, 0.98,
    textstr,
    transform=ax.transAxes,
    fontsize=9,
    horizontalalignment="right",
    verticalalignment="top",
    bbox=dict(boxstyle="round", facecolor="white", alpha=0.85)
)

axes[0].legend()
plt.tight_layout()
plt.savefig("figures/weights_comparison_multiple_vols.pdf")
plt.savefig("figures/weights_comparison_multiple_vols.png")
plt.close()

In [41]:
import matplotlib.pyplot as plt
import numpy as np

# align benchmark weights to returns universe
w_bench_aligned = w_bench.loc[returns_10y.columns, "BenchWeight"]
w_bench_aligned = w_bench_aligned / w_bench_aligned.sum()

# benchmark concentration (Herfindahl index)
bench_concentration = np.sum(w_bench_aligned.values**2)

# sort for readability
w_bench_sorted = w_bench_aligned.sort_values(ascending=False)

plt.figure(figsize=(10, 4))
plt.bar(w_bench_sorted.index, w_bench_sorted.values)

plt.xticks(rotation=45, ha="right")
plt.ylabel("Benchmark Weight")
plt.title("Benchmark Portfolio Weights (DJIA, Market-Cap Weighted)")
plt.grid(axis="y")

# ---- concentration annotation ----
plt.text(
    0.98, 0.95,
    f"Concentration (HHI): {bench_concentration:.3f}",
    transform=plt.gca().transAxes,
    ha="right",
    va="top",
    fontsize=10,
    bbox=dict(boxstyle="round", facecolor="white", alpha=0.85)
)

plt.tight_layout()
plt.savefig("figures/benchmark_weights.pdf")
plt.savefig("figures/benchmark_weights.png")
plt.close()

In [42]:
idxes

[0, 4, 9, 14]

In [50]:
comparison_10y['Volatility'] = comparison_10y['Volatility'].round(2)
comparison_5y['Volatility'] = comparison_5y['Volatility'].round(2)

In [52]:
pd.merge(comparison_5y.iloc[idxes].drop(columns='ESG'), comparison_10y.iloc[idxes].drop(columns='ESG'), how='left', on='Volatility').to_latex()

'\\begin{tabular}{lrrr}\n\\toprule\n & Volatility & ExpectedReturn_x & ExpectedReturn_y \\\\\n\\midrule\n0 & 0.160000 & 0.036180 & 0.041737 \\\\\n1 & 0.200000 & -0.012250 & -0.000228 \\\\\n2 & 0.250000 & -0.101288 & -0.062990 \\\\\n3 & 0.300000 & -0.172680 & -0.078561 \\\\\n\\bottomrule\n\\end{tabular}\n'

In [54]:
bench_exp_return_is_5y = (w_bench_aligned.values @ mu_5y) * 252
bench_exp_return_is_10y = (w_bench_aligned.values @ mu_10y) * 252
print(bench_exp_return_is_5y, bench_exp_return_is_10y)

0.18539828638275482 0.15626010291033715